apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  name: docker-registry
  namespace: tanzu-system-docker-registry
spec:
  rules:
  - host: registry.failk8s.dev
    http:
      paths:
      - backend:
          serviceName: docker-registry
          servicePort: 5000
        path: /
